# Generated by Django 5.0.7 on 2024-07-14 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpeCalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(default='autres', max_length=50),
            preserve_default=False,
        ),
    ]
