# Generated by Django 5.0.7 on 2024-07-22 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpeCalendar', '0006_event_saved_location_alter_event_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carpeCalendar.place'),
        ),
    ]
