# Generated by Django 5.1 on 2024-09-22 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpeCalendar', '0009_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='email_organizer',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='facebook_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
