# Generated by Django 5.1 on 2024-09-22 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpeCalendar', '0010_event_email_organizer_event_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='form_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
