# Generated by Django 5.1.1 on 2024-09-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpeCalendar', '0011_event_form_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='blind_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='deaf_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='neurodiversity_friendly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='pmr_friendly',
            field=models.BooleanField(default=False),
        ),
    ]
