# Generated by Django 5.1 on 2024-10-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpeCalendar', '0013_alter_event_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='granz_filled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='granz_validated',
            field=models.BooleanField(default=False),
        ),
    ]
