# Generated by Django 5.0.7 on 2024-07-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpeCalendar', '0002_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
